# 总投资：50*1.88+30*10.24+20*15.24 = 706
# 潜在投资：$20*20
# 彩蛋：19.19*5

[[quiz]]
name = "桜の咲く音がした"
redpacket = { code = "用于演示的红包口令", price = 0, count = 0 }
description = '''
<style>
.hidden {
  display: inline-block;
  width: 1px;
  overflow: hidden;
  vertical-align: middle;
}

.container {
  display: flex;
  justify-content: space-between;
}

.right {
  display: flex;
  align-items: center;
  flex-direction: column;
  max-width: 50%;
  gap: 2em;
}
.right img {
  object-fit: contain;
  justify-content: space-between;
}
</style>

<div class="container">
<div>

「<a href="https://next.mmf.moe/backlog/2023.html">向新的一年飞驰——记录 2023</a>」

<code><pre>
每题的题号都是一个 UUID
大部分 UUID 是 36 位带横线的格式，但也有部分是 32 位无横线
两种格式都可以正常解析
答案正确即可进入下一题，否则会 404
每一题的网页里都会有一个红包口令。
除本题的口令仅为演示用途之外，其他题的口令均可用于领取红包。

这次的题目每一道都是一首歌名，希望大家听得开心（？
</pre></code>

<span class="hidden">d</span>歩いてる　履き慣れないローファー<br>
<span class="hidden">f</span>駅はもうすぐ<br>
<span class="hidden">9</span>やっと少しだけ覚えてきた<br>
<span class="hidden">e</span>朝は3両目が何となく好き<br>
<!--<span class="hidden">e</span>--><br>
<span class="hidden">0</span>1人　外を眺め　立っている<br>
<span class="hidden">3</span>重たそうに掛けてる　エナメルバッグ<br>
<span class="hidden">7</span>目と目が合った時<br>
<span class="hidden">-</span>気まずくなったんだ<br>
<span class="hidden">4</span>見てない携帯　スクロール<br>
<!--<span class="hidden">3</span>--><br>
<span class="hidden">d</span>桜　咲く音が聞こえ<br>
<span class="hidden">d</span>日常　全てを彩り　景色を変える<br>
<span class="hidden">-</span>見たことのない　ハートの震え<br>
<span class="hidden">4</span>電車の揺れが
<span class="hidden">e</span>Ah　誤魔化してくれたんだ<br>
<span class="hidden">8</span>春の空は　ねえ　雲が　そう　広がり青を隠す<br>
<span class="hidden">f</span>明日の次の　そのもっと先で<br>
<span class="hidden">-</span>青空見えたら　いつか君に伝えたいな<br>
<span class="hidden">b</span>日差しが2人を包んだ<br>
<!--<span class="hidden">b</span>--><br>
<span class="hidden">c</span>同じ制服　着ているけれど<br>
<span class="hidden">3</span>何も知らない<br>
<span class="hidden">-</span>先輩なのか　同級生なのか<br>
<span class="hidden">b</span>ヒントはないのに　ボーッと考えてしまう<br>
<!--<span class="hidden">a</span>--><br>
<span class="hidden">4</span>クラスの女子に人気　ヘアオイル<br>
<span class="hidden">5</span>いつもより温度高め　ストレート<br>
<span class="hidden">4</span>ドアが開いたら<br>
<span class="hidden">0</span>今日もいるのかな<br>
<span class="hidden">7</span>誰も知らない　待ち合わせ<br>
<!--<span class="hidden">d</span>--><br>
<span class="hidden">a</span>ずっと不思議だった<br>
<span class="hidden">3</span>みんなは知ってて　私は知らない色<br>
<span class="hidden">f</span>突然　パッと　現れたカラー<br>
<span class="hidden">f</span>感情のパレット　君でいっぱいで<br>
春の風は　そう　強く　ねえ　吹き付け　気持ち乱す<br>
目が合った時　どう思ったの<br>
いつもの各停　特急に変わった気がした<br>
<br>
ある日　花が咲きました<br>
花の咲かない街でした<br>
それはそれは眩しくて綺麗でした<br>
パステルでビビッドな<br>
初めてのこの気持ちは　きっと…<br>
<br>
会いたかったんだ　ずっと<br>
心の底から惹かれる　特別な人<br>
君に出会って　やっと気付いたよ<br>
開いた桜には「恋」と名前を付けよう<br>
<br>
好きになったんだ<br>
好きが咲いたんだ<br>
それは　日常　全てを彩り　景色を変える<br>
見たことのない　ハートの震え<br>
電車の揺れが
Ah　誤魔化してくれたんだ<br>
春の空は　ねえ　雲が　そう　広がり青を隠す<br>
明日の次の　そのもっと先で<br>
桜が咲く音　君にも聞こえたらいいな<br>
日差しが 2人を包んで　抱きしめた
</div>

<div class="right">
  <iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/6ucm8mk6bJ7bExJJk5LohK?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
  <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/0ImFNEs7P_Q?si=STogNNKzV4H_6rEj" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
  <img src="https://s3-aop.plusmember.jp/prod/public/equallove/contents/discography/3809ea86c2f60c7778c06fe6d53e1188.jpeg" />
</div>

</div>
'''

[[quiz]]
name = "ユエニ"
redpacket = { code = "10343350", price = 1.88, count = 50 }
description = '''
新的一年，红包点击就送，看看你的浏览器是否强壮（？<br><br>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/58AaOttYBBcEtIBgxCVoig?utm_source=generator" width="50%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
'''
links = [
  { name = "点点  ", url = "https://yesterday17.github.io/triangle-2024/framer/index.html" },
  { name = "休息一下（与本题无关）", url = "https://www.bilibili.com/video/BV1aV4y1d7iu" }
]

[[quiz]]
name = "語るなら未来を…"
redpacket = { code = "65828050", price = 10.24, count = 30 }
description = '''
新的一年，跟机器人聊聊未来（？<br><br>
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/track/3RuEQdpv5ys4v6kz5HvH5A?utm_source=generator" width="50%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
'''
links = [
  { name = "聊聊未来  ", url = "https://chat.openai.com/g/g-S3ydBdkkP-melody-flag" },
  { name = "看点视频（与本题无关）", url = "https://www.bilibili.com/video/BV1CC4y1A7f7" }
]

[[quiz]]
name = "2024 新年快乐！"
redpacket = { code = "51705450", price = 20.24, count = 15 }
description = '''
又是一年过去，真是快啊。<br>
很多故事在2023年都画下了中止符，又有一些故事开始。周而复始，构成了完整的一年。<br>
2024年红包的核心主题是「让大家能开开心心领到」，因此今年的选题尽可能减少了前几年的烧脑程度，希望能够变成一些更加纯粹的东西。这个目标究竟有没有实现，就要看今年的红包领取情况了（笑）。<br>
第一题延续前年的题目设计，是简单的白给。由于有些事情意识到地比较晚，所以这道题依然还是小藏了一下。明年的设计应该能更加白给一点（x<br>
第二题的设计想法是大家只要能一直点下去就能拿到红包，不知道有没有人的浏览器足够强壮x<br>
第三题替换了原来的想法，希望大家能够都玩一玩 GPT。GPT 的报销机制我隐藏在了解出题目之后，希望我的钱包没事🙏<br>
总之，今年的新年解谜红包也是顺利地发出来了，对于能看到这里的你来说，这场短暂的解谜之旅能称得上“有趣”吗？欢迎在评论里留下你的想法。<br>
希望大家新的一年都能找到自己想做的事情！当然了，如果能来给我的项目打工就更好不过了（笑）
'''
links = [
  { name = "来打工（？）", url = "https://t.me/+8tokoWliFak1Yjk9" }
]
